"""
Make Visual Atlas (PDF) for universality-discovery
==================================================

Goal
----
Create a single scrollable PDF that collects the most important plots/figures across
the project (the "story so far") in one place.

This intentionally avoids recomputation: it only reads already-generated PNG figures.

Output
------
Writes to:
  universality-discovery/figures/visual_overview/visual_atlas.pdf
  universality-discovery/figures/visual_overview/VISUAL_ATLAS.md
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


ROOT = Path(__file__).resolve().parents[1]  # universality-discovery/
OUT_DIR = ROOT / "figures" / "visual_overview"
OUT_DIR.mkdir(parents=True, exist_ok=True)


@dataclass(frozen=True)
class AtlasPage:
    title: str
    path: Path
    note: str = ""


def _existing_pages(pages: list[AtlasPage]) -> list[AtlasPage]:
    kept: list[AtlasPage] = []
    for p in pages:
        if p.path.exists():
            kept.append(p)
    return kept


def _render_page(pdf: PdfPages, page: AtlasPage) -> None:
    img = plt.imread(page.path)
    fig, ax = plt.subplots(figsize=(11, 6.5))
    ax.imshow(img)
    ax.axis("off")
    fig.suptitle(page.title, y=0.98, fontsize=14, fontweight="bold")
    if page.note:
        fig.text(0.5, 0.02, page.note, ha="center", va="bottom", fontsize=10)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def write_index_md(out_path: Path, pages: list[AtlasPage]) -> None:
    lines: list[str] = []
    lines.append("# Visual Atlas\n")
    lines.append("Generated by `scripts/make_visual_atlas.py`.\n")
    lines.append("## Contents\n")

    for p in pages:
        rel = p.path.relative_to(ROOT).as_posix()
        suffix = f" - {p.note}" if p.note else ""
        lines.append(f"- `{rel}` - {p.title}{suffix}")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    # Keep this list curated: "core results + core diagnostics + core framing".
    pages = _existing_pages(
        [
            AtlasPage(
                "Pipeline Schematic (Measure-Space RG + Diagnostic Gate)",
                ROOT / "figures" / "visual_overview" / "pipeline_schematic.png",
                "Conceptual: model -> random field law -> coarse-graining -> features -> feature-law; gate before interpretation.",
            ),
            AtlasPage(
                "Scale-Invariance vs Universality (Conceptual)",
                ROOT / "figures" / "visual_overview" / "scale_invariance_vs_universality.png",
                "Key lesson: passing the gate (self-consistency) does not guarantee cross-system collapse.",
            ),
            AtlasPage(
                "Exp 50 Distance Summary (Gate-Certified Curves)",
                ROOT / "figures" / "visual_overview" / "exp50_distance_summary.png",
                "KS vs KPZ flat; Burgers vs KPZ non-collapse; KPZ vs KPZ depends on observable; alpha-only behaves as expected.",
            ),
            AtlasPage(
                "Exp 50r: Alpha-Only Positive Control",
                ROOT / "figures" / "visual_overview" / "exp50r_alpha_distributions.png",
                "KPZ-A and KPZ-B alpha distributions overlap; KS is clearly separated.",
            ),
            AtlasPage(
                "IC-Dependence (Exp 27)",
                ROOT / "results" / "exp27_ic_control" / "ic_control_test.png",
                "PC1 separation depends strongly on initial condition sector (flat vs droplet vs stationary).",
            ),
            AtlasPage(
                "Slope-Growth Coupling (Exp 13)",
                ROOT / "figures" / "exp13_slope_growth_coupling.png",
                "Direct physical diagnostic: mean(dh/dt) vs (grad h)^2 differs for KPZ vs EW.",
            ),
            AtlasPage(
                "Coupling Coordinate Discovery (Exp 46)",
                ROOT / "figures" / "coupling_coordinate_scatter.png",
                "PC1 correlates with noise-to-dissipation ratio D/nu^3 across parameter sweeps.",
            ),
            AtlasPage(
                "Information-Geometry Distances vs Scale (Exp 47)",
                ROOT / "figures" / "information_geometry_distances.png",
                "KL / Bhattacharyya distances increase with coarse-graining: operational RG relevance.",
            ),
            AtlasPage(
                "RG-Covariant Embedding (Exp 45b)",
                ROOT / "figures" / "learned_embeddings_pca.png",
                "Learned features can be discriminative while obeying a scale-to-scale map (with anti-collapse constraints).",
            ),
            AtlasPage(
                "KS vs KPZ: Scale-Free Structure Functions (Exp 50n)",
                ROOT / "results_exp50n" / "ks_vs_kpz_scale_free_structure_functions.png",
                "Gate passed; KS vs KPZ remains flat across scales (honest negative result).",
            ),
            AtlasPage(
                "Burgers vs KPZ: Scale-Free Structure Functions (Exp 50o)",
                ROOT / "results_exp50o" / "burgers_vs_kpz_scale_free_structure_functions.png",
                "Gate passed; distance did not collapse (flags mismatch in positive control setup/observable).",
            ),
            AtlasPage(
                "KPZ-A vs KPZ-B: Structure-Function Observable (Exp 50q pilot)",
                ROOT / "results_exp50q_pilot" / "kpzA_vs_kpzB_scale_free_structure_functions.png",
                "Gate passed; distance increased: scale-invariant but non-universal observable (finite-size/corrections).",
            ),
            AtlasPage(
                "KPZ-A vs KPZ-B: Alpha-Only (Exp 50r)",
                ROOT / "results_exp50r" / "kpzA_vs_kpzB_alpha_only.png",
                "With a truly universal 1D feature (alpha), same-class systems overlap; KS separates.",
            ),
            AtlasPage(
                "Early Geometry Snapshot (Exp 05)",
                ROOT / "figures" / "exp05_gradient_space_universality.png",
                "How EW/KPZ organize in low-order gradient observable space (early empirical intuition).",
            ),
            AtlasPage(
                "Wasserstein Distances (Exp 7b)",
                ROOT / "figures" / "exp07b_wasserstein_distances.png",
                "Distances in distribution space show class structure but can be dominated by implementation details.",
            ),
        ]
    )

    pdf_path = OUT_DIR / "visual_atlas.pdf"
    with PdfPages(pdf_path) as pdf:
        for page in pages:
            _render_page(pdf, page)

    index_md = OUT_DIR / "VISUAL_ATLAS.md"
    write_index_md(index_md, pages)

    print(f"Wrote {len(pages)} pages to: {pdf_path}")


if __name__ == "__main__":
    main()
